import { anyVisualBeforeAfter } from './utils/anyVisualBeforeAfter';
import { arLabFilters } from './utils/arLabFilters';
import { cardCounterUpdater } from './utils/cardCounterUpdater';
import { currentYearUpdater } from './utils/currentYearUpdater';
import { dvhTrickFixer } from './utils/dvhTrickFixer';
import { footerLinkPress } from './utils/footerLinkPress';
import { looknigListsAggregator } from './utils/looknigListsAggregator';
import { menuScrollStyler } from './utils/menuScrollStyler';
import { menuVisibilityController } from './utils/menuVisibilityController';
import { parentLinkWrapper } from './utils/parentLinkWrapper';
import { popupSwipers } from './utils/popupSwipers';
import { popupVideoAspectRatio } from './utils/popupVideoAspectRatio';
import { popupVideoLazyLoad } from './utils/popupVideoLazyLoad';
import { studioSwipers } from './utils/studioSwipers';
import { studioSliderLabels } from './utils/studioSliderLabels';
import { loopedVideoRestarter } from './utils/loopedVideoRestarter';
import { embedVideoAspectRatio } from './utils/embedVideoAspectRatio';
import { riveLoader } from './utils/riveLoader';
import './utils/popupVideoAspectRatio.css';
import './utils/riveLoader.css';

window.Webflow ||= [];
window.Webflow.push(() => {
  menuScrollStyler();
  menuVisibilityController();
  anyVisualBeforeAfter();
  popupSwipers();
  popupVideoLazyLoad();
  popupVideoAspectRatio();
  currentYearUpdater();
  cardCounterUpdater();
  arLabFilters();
  studioSwipers();
  studioSliderLabels();
  dvhTrickFixer();
  footerLinkPress();
  looknigListsAggregator();
  parentLinkWrapper();
  loopedVideoRestarter();
  embedVideoAspectRatio();
  riveLoader();
});
